---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.10

suites:
  - name: openvpn
    run_list:
      - recipe[openvpn::default]
      - recipe[openvpn::easyrsa]
    attributes:
