---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.10
  - name: ubuntu-14.04
  - name: ubuntu-13.10
  - name: debian-7.4
  - name: debian-7.6
  - name: debian-7.8

suites:
  - name: openvpn
    run_list:
      - recipe[openvpn::default]
      - recipe[openvpn::easyrsa]
    attributes:
