---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.10

suites:
  - name: default
    run_list:
      - 'recipe[openvpn::default]'
      - 'recipe[openvpn::easyrsa]'
    attributes:
